# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-05 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description2', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=b'documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(default=b'EN-GE', max_length=6)),
                ('translation_launch_hk', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(default=b'EN-GE', max_length=6)),
                ('translation_launch_hk', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=255)),
                ('spanish_text', models.CharField(max_length=255)),
                ('translation', models.CharField(default=b'EN-GE', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordAjaxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=255)),
                ('spanish_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordAjaxModelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=255)),
                ('spanish_text', models.CharField(max_length=255)),
                ('words_status', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WordsUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_active', models.BooleanField(default=False)),
                ('aparitions', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('translation_launch_st', models.IntegerField(default=0)),
                ('translation_launch_lk', models.IntegerField(default=0)),
                ('translation_launch_hk', models.IntegerField(default=0)),
                ('aparitions_hk', models.IntegerField(default=0)),
                ('word_status', models.CharField(choices=[(b'UN', b'Unknown'), (b'ST', b'Started'), (b'LK', b'Lightknown'), (b'HK', b'Heavyknown')], default=b'UN', max_length=2)),
                ('english_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Word')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
