# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_wordsuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
