# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20161208_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordsuse',
            name='autotrans',
        ),
    ]
