# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_wordajax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordajax',
            name='wordRef',
        ),
        migrations.AddField(
            model_name='wordajax',
            name='english_text',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordajax',
            name='spanish_text',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
