# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170103_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordAjax',
            new_name='WordAjaxModel',
        ),
    ]
