# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pruebaexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsuse',
            name='translation_launch',
            field=models.BooleanField(default=False),
        ),
    ]
