# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wordsuse_translation_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsuse',
            name='translation_launch',
            field=models.IntegerField(default=0),
        ),
    ]
