# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170113_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsuse',
            name='word_status',
            field=models.CharField(choices=[('UN', 'Unknown'), ('ST', 'Started'), ('LK', 'Lightknown'), ('HK', 'Heavyknown')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='wordsuse',
            name='english_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Word'),
        ),
        migrations.AlterField(
            model_name='wordsuse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
