# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170224_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAjaxModelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=255)),
                ('spanish_text', models.CharField(max_length=255)),
                ('words_status', models.CharField(max_length=2)),
            ],
        ),
    ]
