# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_wordajaxmodelstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordsuse',
            old_name='translation_launch',
            new_name='translation_launch_hk',
        ),
        migrations.AddField(
            model_name='wordsuse',
            name='translation_launch_lk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordsuse',
            name='translation_launch_st',
            field=models.IntegerField(default=0),
        ),
    ]
