# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-24 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_wordsuse_aparitions_hk'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default='EN-GE', max_length=255),
        ),
    ]
